---
- name: "Provision image"
  hosts: default
  become: true
  roles:
    - ansible-requirements
    - apt-upgrade
    - utf8-locale
    - essential-utils
    - netsoc-dir
    - docker
    - shells
    - apt-autoremove
    - role: lvm-auto-extend
      vars:
        device: "/dev/vda"
        lvm_extended_partition: "2"
        lvm_pv_partition: "5"
        lvm_vg_lv: "system-root"
    - serial-console
    - unpermit-root-login
