- name: "Ensure Vyos Base"
  hosts: all
  roles:
    - role: proxmox-template
      vars: 
        template_name: "netsoc-vyos-router"
        iso_url: "http://packages.vyos.net/iso/release/1.1.8/vyos-1.1.8-amd64.iso"
        iso_file: vyos-1.1.8-amd64.iso
        iso_checksum: sha1:ff4c8e1822e653d8d85f4a90f30c6d2ac047514c
        provision_directory: ./proxmox-templates/netsoc-vyos-router
  vars_files:
    - vars/proxmox.yml
    - vars/secrets.yml