---
- name: Ensure Python Consul libs
  become: yes
  pip:
    name: 
      - python-consul
      - pyhcl
    state: present

- name: Ensure /netsoc-neo/docker-data/consul created with 0770 for persistent data
  become: yes
  file:
    path: /netsoc-neo/docker-data/consul
    owner: netsoc
    group: netsoc
    mode: 0770 # drwxrwx--- needed due to permissions in Consul container
    state: directory

- name: Ensure Hashicorp Consul network
  when: inventory_hostname in groups.swarm_creators
  become: yes
  docker_network:
    name: consul
    driver: overlay
    attachable: yes

- name: Ensure Consul Config in Docker Swarm Secrets
  run_once: true
  become: yes
  docker_secret:
    name: consul_config.hcl
    data: "{{ lookup('template', './files/config.hcl') }}"
  register: result
  ignore_errors: true

- name: Remove Consul Config Secret from Swarm Service to update the Secret
  become: yes
  docker_stack:
    state: absent
    absent_retries: 5
    name: consul
  when: result is failed

- name: Retry setting Consul Config in Docker Swarm Secrets if necessary
  run_once: true
  when: result is failed
  become: yes
  docker_secret:
    name: consul_config.hcl
    data: "{{ lookup('template', './files/config.hcl') }}"

- name: Ensure Hashicorp Consul cluster
  run_once: true
  become: yes
  docker_stack:
    state: present
    name: consul
    compose: 
      - version: '3.7'
        secrets:
          consul_config.hcl:
            external: true
        networks:
          consul:
            external: true
          traefik:
            external: true
        services:
          server_bootstrap:
            hostname: server-bootstrap
            container_name: consul_server_bootstrap
            image: consul:1.6.1
            networks:
              traefik:
              consul:
                aliases:
                  - consul
            command: 'agent -config-file=/run/secrets/consul_config.hcl -rejoin'
            hostname: '{% raw %}{{ .Node.Hostname }}.consul.netsoc.co{% endraw %}'
            volumes:
              - /netsoc-neo/docker-data/consul:/consul/data
            environment:
              - CONSUL_BIND_INTERFACE=eth0
            secrets:
              - consul_config.hcl
            deploy:
              endpoint_mode: dnsrr # Needed to get cluster to not rely on pre-known IPs
              mode: global
              placement:
                constraints:
                  - node.role == manager
                  - node.hostname == {{ inventory_hostname }}
              restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 60s
              update_config:
                parallelism: 1 # operate on one instance at a time to maintain stable quorum (in theory)
                delay: 20s
                order: start-first # want to bring up new instance to always maintain quorum
              labels:
                - "traefik.enable=true"
                - "traefik.http.routers.consul.rule=Host(`consul.netsoc.co`)"
                - "traefik.http.services.consul-service.loadbalancer.server.port=8500"
                - "traefik.http.services.consul-service.loadBalancer.healthCheck.path=/v1/status/leader"
                - "traefik.http.services.consul-service.loadBalancer.healthCheck.timeout=3s"
                - "traefik.http.services.consul-service.loadBalancer.healthCheck.interval=10s"
                - "traefik.http.routers.consul.tls.certResolver=letsencrypt"
                - "traefik.http.routers.consul.service=consul-service"
                - "traefik.docker.network=traefik"

- name: Wait for Leader elected
  run_once: true
  uri:
    url: https://consul.netsoc.co:444/v1/status/leader
    return_content: yes
    validate_certs: no
  register: response
  until: response.content_length != "2" and response.status == 200
  retries: 10

- name: Push Consul Agent token
  run_once: true
  consul_acl_prefix:
    scheme: https
    host: consul.netsoc.co
    port: 444
    validate_certs: no
    name: Agent Token - inter-agent comms # why doesnt this get set? idk
    token_type: management
    token: "{{ consul_agent_token }}"
    mgmt_token: "{{ consul_master_token }}"
    rules:
      - node: ""
        policy: write
      - service: ""
        policy: read
