---
- name: Ensure /netsoc-neo/docker-data/consul created with 0700
  become: yes
  file:
    path: /netsoc-neo/docker-data/consul
    owner: root
    group: root
    mode: 0700 # drwx----
    state: directory

- name: Ensure Hashicorp Consul network
  become: yes
  docker_network:
    name: consul
    driver: overlay
    attachable: yes

- name: Ensure Hashicorp Consul cluster
  become: yes
  docker_stack:
    state: present
    name: consul
    compose: 
      - version: '3.5'
        networks:
          consul:
            external: true
          traefik:
            external: true
        services:
          server_bootstrap:
            hostname: server-bootstrap
            container_name: consul_server_bootstrap
            image: consul:1.6.1
            networks:
              traefik:
              consul:
                aliases:
                  - consul.cluster
            command: agent -server -bootstrap-expect 3 -retry-join consul.cluster -client 0.0.0.0 -bind {% raw %}'{{ GetInterfaceIP "eth0" }}'{% endraw %} -ui
            environment:
              - CONSUL_BIND_INTERFACE=eth0
            deploy:
              endpoint_mode: dnsrr # Needed to get cluster to not rely on pre-known IPs
              mode: global
              placement:
                constraints:
                  - node.role == manager
                  - node.hostname == {{ inventory_hostname }}
              restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
              labels:
                - "traefik.enable=true"
                - "traefik.http.routers.consul.rule=Host(`consul.netsoc.co`)"
                - "traefik.http.services.consul-service.loadbalancer.server.port=8500"
                - "traefik.http.routers.consul.tls.certResolver=letsencrypt"
                - "traefik.http.routers.consul.service=consul-service"
                - "traefik.docker.network=traefik"
