
# - name: "Build Vyos ISO (OpenStack ISO with NoCloud cloud-init support)"
#   hosts: proxmox_master
#   tasks:
#     - shell: git clone https://github.com/vyos/vyos-build.git
#       args:
#         chdir: /root/NaC-repo
#     - shell: docker build -t vyos-builder docker
#       args:
#         chdir: /root/NaC-repo/vyos-build
#     - shell: docker run --rm -it --privileged -v $(pwd):/vyos -w /vyos vyos-builder bash -c "./configure && sudo make openstack"
#       args:
#         chdir: /root/NaC-repo/vyos-build

- name: "Copy ISO to all hosts"
  hosts: proxmox_hosts
  become: yes
  tasks:
    - copy:
        src: /root/NaC-repo/vyos-build/build/live-image-amd64.hybrid.iso
        dest: /var/lib/vz/template/iso/vyos-1.3-rolling-amd64.iso