---
- name: "Setup DNS"
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - vars/ip_allocation.yml
    - vars/cloudflare.yml
    - vars/secrets.yml
  tasks:
    - name: "Add DNS records"
      cloudflare_dns:
        zone: "{{ item.zone }}"
        type: "{{ item.type }}"
        record: "{{ item.record }}"
        value: "{{ item.value }}"
        state: present
        account_email:    "{{ cloudflare_api_email }}"
        account_api_token: "{{ cloudflare_api_key }}"
      with_items:
        # A record for use before the DNS is first setup on auth
        - { zone: "netsoc.co", type: A,      record: "ipa.vm", value: "{{ ip_allocation.freeipa_base }}" }
        - { zone: "netsoc.co", type: NS,     record: "vm",     value: "ipa.vm" }
        