---
- name: "Setup DNS"
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - vars/cloudflare.yml
    - vars/secrets.yml
  tasks:
    - name: "Add DNS records"
      cloudflare_dns:
        zone: "{{ item.zone }}"
        type: "{{ item.type }}"
        record: "{{ item.record }}"
        value: "{{ item.value }}"
        state: present
        account_email:    "{{ cloudflare_api_email }}"
        account_api_token: "{{ cloudflare_api_key }}"
      with_items:
          # NS for clients
          - { zone: "netsoc.co", type: A,      record: "ipa",     value: "10.0.30.2"     }
          - { zone: "netsoc.co", type: NS,     record: "vm", value: "ipa.netsoc.co" }
          