---
- name: "Setup DNS"
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - vars/cloudflare.yml
    - vars/secrets.yml
  tasks:
    - import_tasks: dns.yml
  tags:
    - install-base
    - install-services
    - update-dns