# Please use IP addresses for each server
# This is done because DNS may not be configured when the playbook is ran
#
# Keep the ansible hostname as strictly the server name
# These are used to setup DNS records and related
# i.e only use "feynman", not "feynman.netsoc.co"

all:
  hosts:
    feynman:
      ansible_host: 84.39.234.53
      ansible_ssh_port: 22
      ansible_ssh_user: netsoc
      ansible_ssh_private_key_file: "./keys/feynman/id_rsa"
      ansible_python_interpreter: "/usr/bin/python3"
