---
- name: "Setup DNS"
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - vars/cloudflare.yml
  tasks:
    - import_tasks: dns.yml
  tags:
    - install-base
    - install-services
  
- name: "Install requirements on all hosts"
  hosts: all
  become: yes

  # Assume we're doing a completely new install from a fresh server
  # Fact gathering requires python, which the server may not have
  gather_facts: no
  
  roles:
    - ansible-requirements  # Installs python2.7, 3
    - ubuntu-universe       # Add's ubuntu universe source (which has python-pip, etc..)
    - essential-utils
    - docker
    - apt-autoremove        # Remove unused deps if they changed after updates
  tags:
    - install-base
    - install-packages

- name: "Copy netsoc-neo"
  hosts: all
  become: yes
  gather_facts: yes
  roles:
    - netsoc-neo-dir
  tags:
    - install-base
    - install-services

- name: "Setup Traefik"
  hosts:
    - feynman
  # ONLY uncomment for non-root servers (not feynman)!
  # CF API keys are exposed in the Docker container env.
  # /users can rob our SSL private key from /etc/traefik/acme.json!!!
  # vars_files:
  #   - vars/cloudflare.yml  # Used for LetsEncrypt
  roles:
    - traefik
  tags:
    - install-base
    - install-services

- name: "Setup Portainer (feynman edition)"
  hosts:
    - feynman
  roles:
    - portainer-feynman