---
- name: "Setup DNS"
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - vars/cloudflare.yml
  tasks:
    - import_tasks: dns.yml
  tags:
    - install-base
    - install-services
  
- name: "Ensure base install"
  hosts: all

  # Assume we're doing a completely new install from a fresh server
  # Fact gathering requires python, which the server may not have
  gather_facts: no
  
  roles:
    - ansible-requirements  # Installs python2.7, 3 and then gathers facts
    - netsoc-neo-dir        # Set's up /netsoc-neo/ for storing our central files
    - paramiko-fix          # Fixes: # https://github.com/paramiko/paramiko/pull/1311
                            # Remove and upgrade paramiko when this is merged
    - ubuntu-universe       # Ubuntu community repos
    - essential-utils       # iotop, htop, git, node, etc...
    - shells
    - fail2ban
    
    - docker                # Docker APT, Docker, etc...
    - apt-autoremove        # Clean up any unused deps
  tags:
    - install-base
    - install-packages

- name: "Setup Traefik"
  hosts: feynman
  roles:
    - traefik
  tags:
    - install-base
    - install-services

- name: "Setup Portainer"
  hosts: feynman
  roles:
    - portainer
  vars:
    portainer_traefik_host_rule: "feyn-portainer.netsoc.dev"
  tags:
    - install-base
    - install-services

# - name: "Setup FreeIPA Server"
#   hosts: feynman
#   roles:
#     - freeipa-server
#   vars:
#     ipa_realm: NETSOC.DEV
#     ipa_server_hostname: feyn-ipa.netsoc.dev
#     ipa_traefik_host_rule: feyn-ipa.netsoc.dev
#   vars_files:
#     - vars/freeipa.yml  # passwords

# - name: "Setup FreeIPA Clients"
#   hosts: feynman
#   roles:
#     - freeipa-client
#   vars:
#     ipa_realm: NETSOC.DEV
#     ipa_domain: netsoc.dev
#     ipa_server_hostname: feyn-ipa.netsoc.dev
#     ipa_client_hostname: "{{ inventory_hostname }}.netsoc.dev"
#   vars_files:
#     - vars/freeipa.yml  # passwords

