---
- name: "Setup DNS"
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - vars/cloudflare.yml
  tasks:
    - import_tasks: dns.yml
  tags:
    - install-base
    - install-services
  
- name: "Install requirements on all hosts"
  hosts: all
  become: yes

  # Assume we're doing a completely new install from a fresh server
  # Fact gathering requires python, which the server may not have
  gather_facts: no
  
  roles:
    - ansible-requirements  # Installs python2.7, 3 and then gathers facts
    - ubuntu-universe       # Add's ubuntu universe source (which has python-pip, etc..)
    - essential-utils       # git, htop, etc...
    - docker
    - apt-autoremove        # Remove unused deps if they changed after upgrades
  tags:
    - install-base
    - install-packages

- name: "Setup the /netsoc-neo/ dir"
  hosts: all
  become: yes
  gather_facts: yes
  roles:
    - netsoc-neo-dir
  tags:
    - install-base
    - install-services

- name: "Setup Traefik"
  hosts: feynman
  roles:
    - traefik
  tags:
    - install-base
    - install-services

- name: "Setup Portainer"
  hosts: feynman
  roles:
    - portainer
  vars:
    portainer_host_rule: feyn-portainer.netsoc.dev
  tags:
    - install-base
    - install-services

- name: "Setup FreeIPA Server"
  hosts: feynman
  roles:
    - freeipa-server
  vars:
    ipa_realm: NETSOC.DEV
    ipa_hostname: ipa-poc.netsoc.dev
    ipa_traefik_host_rule: ipa-poc.netsoc.dev
  vars_files:
    - vars/freeipa.yml  # passwords
