- name: "Ensure data disk made"
  hosts: nfs
  become: yes
  roles:
    - role: simple-disk
      vars:
        device: "/dev/vdb"
        part_size: "100%"
        fstype: "ext4"
        mount_path: "/srv/nfs"
        mount_opts: "rw"

- name: "Ensure server"
  hosts: nfs
  become: yes
  tasks:
    - file:
        path: "/srv/nfs/docker-data"
        state: directory
  roles:
    - role: nfs-server-docker
      vars:
        nfs_disk: "/srv/nfs"
        exports: |
          /nfs/docker-data/*                                   10.0.30.0/24(rw,sync,no_root_squash,sec=krb5p)
