---

- name: "Ensure Docker Swarm created" 
  hosts: docker_managers
  roles:
    - role: docker-swarm-create
      when: "ansible_play_hosts_all.index(inventory_hostname) == 0"
    - role: docker-swarm-enroll-manager
      when: "ansible_play_hosts_all.index(inventory_hostname) > 0"
      vars:
        swarm_creator: "{{ groups['docker_managers'][0] }}"

- name: "Ensure Docker Swarm workers enrolled"
  hosts: docker_workers
  roles:
    - docker-swarm-enroll-worker
  vars:
    swarm_creator: "{{ groups['docker_managers'][0] }}"
