- name: "Ensure IPA server disk mounted"
  hosts: auth
  become: yes
  roles:
    - role: simple-disk
      vars:
        device: "/dev/vdb"
        partition_size: "100%"
        fstype: "ext4"
        mount_path: "/mnt/freeipa-disk"
        mount_opts: "rw"
    - role: freeipa-server-docker
      vars:
        ip: "{{ ansible_ens18.ipv4.address }}"
        mount: "/mnt/freeipa-disk"
        realm: IPA.NETSOC.CO
        domain: ipa.netsoc.co
        server_hostname: ipa-container.ipa.netsoc.co
        ds_password: "{{ freeipa_ds_password }}"
        admin_password: "{{ freeipa_admin_password }}"
  vars_files:
    - "vars/ip_allocation.yml"
    - "vars/freeipa.yml"
    - "vars/secrets.yml"

- name: "Enroll Auth in IPA server"
  hosts: auth
  roles:
    - role: freeipa-client
      vars:
        realm: IPA.NETSOC.CO
        server_hostname: ipa.netsoc.co
        client_hostname: auth.ipa.netsoc.co
        domain: ipa.netsoc.co
        ds_password: "{{ freeipa_ds_password }}"
        admin_password: "{{ freeipa_admin_password }}"
  vars_files:
    - "vars/freeipa.yml"
    - "vars/secrets.yml"