- name: "Ensure Vyos Template"
  hosts: proxmox_hosts
  roles:
    - role: packer-proxmox-template
      vars: 
        template_name: "netsoc-vyos-router"
        provisioning_directory: ./packer/netsoc-vyos-router
        provisioning_host: lovelace
        cloudinit: yes
        packer_vars:
          iso_file: vyos-amd64.iso
          provisioning_vyos_password: "{{ provisioning_vyos_password }}"
  vars_files:
    - vars/packer.yml
    - vars/proxmox.yml
    - vars/secrets.yml