- name: "Ensure Vyos Template"
  hosts: proxmox_hosts
  roles:
    - role: packer-proxmox-template
      vars: 
        template_name: "netsoc-vyos-router"
        provision_directory: ./packer/netsoc-vyos-router
        cloudinit: yes
        packer_vars:
          iso_file: vyos-1.3-rolling-amd64.iso
          vyos_password: "{{ vyos_password }}"
  vars_files:
    - vars/packer.yml
    - vars/proxmox.yml
    - vars/secrets.yml