---
- name: Update APT cache
  become: yes
  apt:
    update_cache: yes

- name: "Ensure iotop, iftop, htop, git, nodejs, ipython, npm, JDK, ruby installed"
  become: yes
  apt:
    name:
      - iotop
      - iftop
      - htop
      - git
      - nodejs
      - ipython
      - npm
      - default-jdk
      - ruby
    state: latest