---
- name: Update APT cache
  apt:
    update_cache: yes

- name: "Ensure iotop, iftop, htop installed"
  apt:
    name:
      - iotop
      - iftop
      - htop
    state: latest

- name: "Ensure git installed"
  apt:
    name:
      - git
    state: latest