---

- name: "Install LVM Auto Extend Service"
  copy:
    content: |
      [Unit]
      Description=LVM Auto Extend

      [Service]
      Type=oneshot
      ExecStart=parted ---pretend-input-tty resizepart {{ device }} resizepart {{ lvm_extended_partition }} 100% && \
                parted ---pretend-input-tty resizepart {{ device }} resizepart {{ lvm_pv_partition }}  100%      && \
                pvresize {{ device }}{{ lvm_pv_partition }}                                                      && \
                lvextend -r /dev/mapper/{{ lvm_vg_lv }} -l +100%FREE

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/lvm-auto-extend.service

- name: "Enable LVM Auto Extend Service"
  systemd:
    name: lvm-auto-extend
    enabled: yes