- name: "Check if zpool {{ pool }} exists / create it if it doesn't"
  become: yes
  block:
    - zpool_facts:
        pool: "{{ pool }}"
      register: zpool_result 
  rescue:
    - command:
        cmd: "zpool create -o autoexpand=on {{ pool }} {{ device }} -m {{ mount }}"

- name: "Create zfs {{ item }} in {{ pool }}"
  become: yes
  zfs:
    name: "{{ pool }}/{{ item }}"
    state: present
  with_items: "{{ fs }}"

- name: "755 {{ item }} in {{ pool }}"
  become: yes
  file:
    name: "/{{ pool }}/{{ item }}"
    mode: 0755
  with_items: "{{ fs }}"

- name: "Configure intervals for zfs-auto-snapshot"
  become: yes
  shell: |
    #!/bin/bash
    zfs set com.sun:auto-snapshot=true {{ pool }}/{{ item }}
    zfs set com.sun:auto-snapshot:monthly={{ snapshot.monthly | default('true') | bool | lower }} {{ pool }}/{{ item }}
    zfs set com.sun:auto-snapshot:weekly={{ snapshot.weekly | default('true') | bool | lower }}   {{ pool }}/{{ item }}
    zfs set com.sun:auto-snapshot:daily={{ snapshot.daily | default('true') | bool | lower }}     {{ pool }}/{{ item }}
    zfs set com.sun:auto-snapshot:hourly={{ snapshot.hourly | default('false') | bool | lower }}    {{ pool }}/{{ item }}
    zfs set com.sun:auto-snapshot:frequent={{ snapshot.frequent | default('true') | bool | lower }} {{ pool }}/{{ item }}
  with_items: "{{ fs }}"