---

- name: Ensure /netsoc-neo/docker-data/traefik created with 0700
  become: yes
  file:
    path: /netsoc-neo/docker-data/traefik
    owner: netsoc
    group: netsoc
    mode: 0700 # drwx----
    state: directory

- name: Ensure config in /netsoc-neo/docker-data/traefik
  become: yes
  copy:
    src: "{{ item.src }}"
    dest: "/netsoc-neo/docker-data/traefik/{{ item.path }}"
    owner: netsoc
    group: netsoc
    mode: "{{ item.mode }}"
    backup: yes
  with_filetree:
    - files/
  when: item.state == "file"

- name: Ensure Traefik Docker container
  become: yes
  docker_compose:
    project_name: traefik
    state: present
    restarted: true
    recreate: always
    definition:
      version: "3.5"
      networks:
        traefik:
          name: traefik
      services:
        traefik:
          image: traefik:alpine
          ports:
            - 80:80
            - 443:443
            - 8084:8084
          volumes:
            - /netsoc-neo/docker-data/traefik:/etc/traefik
            - /var/run/docker.sock:/var/run/docker.sock
          networks:
            - traefik
        whoami:
          image: emilevauge/whoami
          networks: 
            - traefik
          labels:
            traefik.enable: true
            traefik.frontend.rule: "Host: whoami.netsoc.dev"
