
- name: "Install auto-snapshot requirements"
  become: yes
  apt:
    name:
      - zfs-auto-snapshot

- name: "Modify zfs-auto-snapshot script to set our options"
  become: yes
  blockinfile:
    dest: /usr/sbin/zfs-auto-snapshot
    content: |
      opt_backup_full=''
      opt_backup_incremental=''
      opt_default_exclude='1'
      opt_dry_run=''
      opt_event='-'
      opt_fast_zfs_list='1'
      opt_keep=''
      opt_label=''
      opt_prefix='snapshot'
      opt_recursive=''
      opt_sep='-'
      opt_setauto=''
      opt_syslog=''
      opt_skip_scrub=''
      opt_verbose=''
      opt_pre_snapshot=''
      opt_post_snapshot=''
      opt_do_snapshots='1'
    insertafter: "^opt_do_snapshots" # insert after their list of defaults, so our list immediately overrides it
