---

- name: Ensure /netsoc-neo/docker-data/freeipa created with 0755
  become: yes
  file:
    path: /netsoc-neo/docker-data/freeipa
    owner: netsoc
    group: netsoc
    mode: 0777 # drwx-------
    state: directory

# Required for NetsocAdmin2, we force ldap to use CRYPT passwords
- name: Copy password algorithm change
  copy:
    src: "files/freeipa-01-password-algorithm.update"
    dest: "/netsoc-neo/docker-data/freeipa-01-password-algorithm.update"

- name: Ensure FreeIPA server container
  become: yes
  docker_container:
    name: freeipa
    state: started
    restart: yes
    recreate: yes
    image: freeipa/freeipa-server
    hostname: "{{ ipa_server_hostname }}"
    read_only: true
    command: --unattended --realm={{ ipa_realm }} --ds-password={{ ipa_ds_password }} --admin-password={{ ipa_admin_password }}
    env:
      IPA_SERVER_HOSTNAME: "{{ ipa_server_hostname }}"
    ports:
      # - "80:80"
      # - "443:443"
      - "389:389"   # ldap
      - "636:636"   # ldaps
      - "88:88"     # kerberos
      - "464:464"   # kpasswd
      - "749:749"   # kpasswd
      - "123:123"   # ntp
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "/etc/machine-id:/etc/machine-id:ro"
      - "/netsoc-neo/docker-data/freeipa:/data:Z"
      - "/netsoc-neo/docker-data/freeipa-01-password-algorithm.update:/usr/share/ipa/updates/01-password-algorithm.update"
    tmpfs:
      - "/run"
      - "/tmp"
    sysctls:
      net.ipv6.conf.lo.disable_ipv6: 0
      # Fixes:
      # DEBUG The ipa-server-install command failed, exception: 
      # RuntimeError: IPv6 stack is enabled in the kernel but there is no interface that has ::1 address assigned.
      # Add ::1 address resolution to "lo" interface. You might need to enable IPv6 on the interface "lo" in sysctl.conf.
    networks:
      - name: "traefik"
    labels:
      traefik.enable: "true"
      traefik.docker.network: "traefik"
      traefik.frontend.rule: "Host: {{ ipa_traefik_host_rule }}"
      traefik.port: "443"
      traefik.protocol: "https"

  #docker_compose:
  #   project_name: freeipa
  #   state: present
  #   restarted: true
  #   recreate: never
  #   definition:
  #     version: "3.5"
  #     networks:
  #       traefik:
  #         external: true
  #     services:
  #       freeipa:
  #         container_name: "{{ ipa_container_name }}"
  #         image: freeipa/freeipa-server
  #         command: --unattended --realm={{ ipa_realm }} --ds-password={{ ipa_ds_password }} --admin-password={{ ipa_admin_password }}
  #         hostname: "{{ ipa_server_hostname }}"
  #         read_only: true
  #         environment:
  #           IPA_SERVER_HOSTNAME: "{{ ipa_server_hostname }}"
  #           # IPA_SERVER_IP: "192.168.1.50"
  #         volumes:
  #           - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  #           - "/etc/machine-id:/etc/machine-id"
  #           - "/netsoc-neo/docker-data/freeipa:/data"
  #           - "/netsoc-neo/docker-data/freeipa-01-password-algorithm.update:/usr/share/ipa/updates/01-password-algorithm.update"
  #         tmpfs:
  #           - "/run"
  #           - "/tmp"
  #         sysctls:
  #           net.ipv6.conf.lo.disable_ipv6: 0
  #           # Fixes:
  #           # DEBUG The ipa-server-install command failed, exception: 
  #           # RuntimeError: IPv6 stack is enabled in the kernel but there is no interface that has ::1 address assigned.
  #           # Add ::1 address resolution to "lo" interface. You might need to enable IPv6 on the interface "lo" in sysctl.conf.
  #         networks:
  #           default:
  #           traefik:
  #         ports:
  #           # - "80:80"
  #           # - "443:443"
  #           - "389:389"   # ldap
  #           - "636:636"   # ldaps
  #           - "88:88"     # kerberos
  #           - "464:464"   # kpasswd
  #           - "749:749"   # kpasswd
  #           - "123:123"   # ntp
  #         labels:
  #           traefik.enable: true
  #           traefik.docker.network: traefik
  #           traefik.frontend.rule: "Host: {{ ipa_traefik_host_rule }}"
  #           traefik.port: "443"
  #           traefik.protocol: "https"

- name: Wait for install to finish (8-12 minutes)
  become: yes
  wait_for:
    path: /netsoc-neo/docker-data/freeipa/var/log/ipa-server-configure-first.log
    search_regex: "FreeIPA server configured."
    timeout: 1200 # 20 minutes

# We copy the self-signed CA cert that FreeIPA generated to the Traefik server
# we cannot use the Netsoc ssl certs or they'll be stolen cause root access is allowed on feynman
- name: Copy httpd certs from FreeIPA to Traefik (get IPA httpd encrypted cert password)
  become: yes
  copy:
    src: "/netsoc-neo/docker-data/freeipa/var/lib/ipa/passwds/feyn-ipa.netsoc.dev-443-RSA"
    dest: /netsoc-neo/docker-data/traefik/httpd.pin
    remote_src: yes

- name: Copy httpd certs from FreeIPA to Traefik (copy .crt) 
  become: yes
  copy:
    src: /netsoc-neo/docker-data/freeipa/var/lib/ipa/certs/httpd.crt
    dest: /netsoc-neo/docker-data/traefik/httpd.crt
    remote_src: yes

- name: Copy httpd certs from FreeIPA to Traefik (copy .key) 
  become: yes
  copy:
    src: /netsoc-neo/docker-data/freeipa/var/lib/ipa/private/httpd.key
    dest: /netsoc-neo/docker-data/traefik/httpd.key.encrypted
    remote_src: yes

- name:
  become: yes
  shell: "openssl rsa -in httpd.key.encrypted -out httpd.key -passin file:httpd.pin"
  args:
    chdir: /netsoc-neo/docker-data/traefik/