---

- name: "Ensure FreeIPA client dependencies"
  become: yes
  apt:
    name:
      - freeipa-client
      - freeipa-admintools
    state: latest
    update_cache: yes

- name: "Enroll server as a FreeIPA client"
  become: yes
  command: "ipa-client-install --unattended --server {{ ipa_server_hostname }} --domain {{ ipa_domain }} --realm {{ ipa_realm }} --hostname {{ ipa_client_hostname }} --principal admin --password {{ ipa_admin_password }}" 
  register: result

- debug: msg="{{ result.stdout }}"
- debug: msg="{{ result.stderr }}"

- name: "Update nsswitch.conf to use Files, SSSD for auth"
  become: yes
  copy:
    content: |
      passwd:         compat systemd sss
      group:          compat systemd sss
      shadow:         compat sss
      gshadow:        files sss

      hosts:          files dns
      networks:       files

      protocols:      db files
      services:       db files
      ethers:         db files
      rpc:            db files

      netgroup:       nis
      sudoers:        files sss
    dest: "/etc/nsswitch.conf"