[http.routers]
  [http.routers.leela-fallback]
    rule = "HostRegexp(`{.*}.netsoc.dev`) || HostRegexp(`www.{.*}.netsoc.dev`) || HostRegexp(`{.*}.netsoc.co`) || HostRegexp(`www.{.*}.netsoc.co`)"
    entryPoints = ["web-secure"]
    priority = 1
    service = "leela-fallback-service@file"

  [http.routers.leela-fallback.tls]
    certResolver = "letsencrypt"

    [[http.routers.leela-fallback.tls.domains]]
      main = "netsoc.co"
      sans = ["*.netsoc.co", "*.netsoc.dev", "netsoc.dev"]

[http.services]
  [http.services.leela-fallback-service.loadBalancer]
    [[http.services.leela-fallback-service.loadBalancer.servers]]
      url = "http://leela.netsoc.co/"