---

- name: Ensure /netsoc-neo/docker-data/portainer exists with 0755
  become: yes
  file:
    path: /netsoc-neo/docker-data/portainer
    owner: root
    group: root
    mode: 0777
    state: directory


- name: Ensure Portainer container
  become: yes
  docker_compose:
    project_name: portainer
    state: present
    restarted: true
    recreate: always
    definition:
      version: "3.5"
      networks:
        traefik:
          external:
            name: traefik
      services:
        portainer:
          container_name: "portainer"
          image: portainer/portainer:1.22.0
          volumes:
            - /netsoc-neo/docker-data/portainer:/data
            - /var/run/docker.sock:/var/run/docker.sock
          networks:
            - traefik
            - default
          labels:
            traefik.enable: true
            traefik.docker.network: traefik
            traefik.frontend.rule: "Host: {{ portainer_traefik_host_rule }}"
            traefik.port: "9000"
            traefik.protocol: "http"