- name: Add dnsmasq
  apt:
    name: dnsmasq
    state: latest

- name: Enable dnsmasq conf dir
  shell: echo 'conf-dir=/etc/dnsmasq.d/,*.conf' >> /etc/dnsmasq.conf

- name: Template proxmox.conf (dnsmasq entries)
  template:
    src: "files/proxmox.conf.j2"
    dest: "/etc/dnsmasq.d/proxmox.conf"

- name: Insert bridge into /etc/network/interfaces.d
  copy:
    path: /etc/network/interfaces.d/01-packer-provisioning-dhcp-bridge
    content: |
      # Packer provisioning subnetwork
      auto {{ bridge_interface }}
      iface {{ bridge_interface }} inet static

      address {{ bridge_address }}
      netmask {{ bridge_netmask }}
      bridge_ports none
      bridge_stp off
      bridge_fd 0
      post-up echo 1 > /proc/sys/net/ipv4/ip_forward
      post-up iptables -t nat -A POSTROUTING -s '{{ bridge_address }}/{{ bridge_netmask }}' -o {{ nat_interface }} -j MASQUERADE
      post-up iptables -t raw -I PREROUTING -i fwbr+ -j CT --zone 1
      post-down iptables -t nat -D POSTROUTING -s '{{ bridge_address }}/{{ bridge_netmask }}' -o {{ nat_interface }} -j MASQUERADE && iptables -t raw -D PREROUTING -i fwbr+ -j CT --zone 1
   
- name: Reload networking
  command: ifreload -a

- name: Start dnsmasq
  systemd:
    name: dnsmasq
    state: restarted
