---
- name: Get current mounted Secret Engines
  uri:
    url: "{{ hashivault_url }}/v1/sys/mounts"
    headers:
      X-Vault-Token: "{{ hashivault_root_token }}"
    method: GET
    validate_certs: no
    return_content: yes
  register: engines
    
- name: Enable KV Engine at docker-registry/
  when: ('docker_registry/' not in engines.json)
  uri:
    url: "{{ hashivault_url }}/v1/sys/mounts/docker_registry"
    headers:
      X-Vault-Token: "{{ hashivault_root_token }}"
    method: POST
    validate_certs: no
    body_format: json
    status_code: [204]
    body:
      type: kv
      version: "2"
  register: resp