---
- name: Ensure Python 3
  become: yes
  raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
  register: result
  changed_when: "result.rc != 0"

- name: Gather facts
  setup:

- name: Ensure python3-distutils
  apt:
    name: python3-distutils

- name: Ensure pip installed
  become: yes
  raw: "curl https://bootstrap.pypa.io/get-pip.py | python3 get-pip.py"

- name: Ensure upgraded pip and ansible pip requirements
  become: yes
  pip:
    name:
      - pip
      - ansible
    state: latest
    extra_args: --upgrade
