defaultEntryPoints = ["http", "https"]

# Don't bother with HTTPS intraserver
# We're using Traefik as an SSL termination proxy
insecureSkipVerify = true
logLevel = "ERROR"

[traefikLog]
  filePath = "/etc/traefik/traefik.log"
  format   = "json"

[accessLog]
  filePath = "/etc/traefik/access.log"
  format = "json"

[api]
  entryPoint = "traefik"
  dashboard = true
  debug = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
  
  [entryPoints.traefik]
  address = ":8079"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "netsoc.dev"
exposedByDefault = false