---

- name: Ensure freeipa-data dir
  become: yes
  file:
    path: "{{ mount }}/freeipa-data"
    owner: root
    group: root
    mode: 0770
    state: directory

- name: Ensure freeipa-mods dir
  become: yes
  file:
    path: "{{ mount }}/freeipa-mods"
    owner: root
    group: root
    mode: 0770
    state: directory

- name: Ensure HTTP redirect disabler
  become: yes
  copy:
    src: "files/ipa-rewrite.conf"
    dest: "{{ mount }}/freeipa-mods/ipa-rewrite.conf"

- name: Ensure FreeIPA server container
  become: yes
  docker_container:
    name: freeipa_server
    state: started
    recreate: yes
    image: freeipa/freeipa-server
    read_only: true
    hostname: "{{ domain }}"
    command: >
      --unattended
      --realm={{ realm }}
      --ds-password={{ ds_password }}
      --admin-password={{ admin_password }}
      --setup-dns
      --forwarder="1.1.1.1"
      --forward-policy=only
      --ssh-trust-dns
      --no-host-dns
      --allow-zone-overlap
    env: # environment:
      IPA_SERVER_HOSTNAME: "{{ domain }}"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "/etc/machine-id:/etc/machine-id"
      - "{{ mount }}/freeipa-data/:/data"
      - "{{ mount }}/freeipa-mods/ipa-rewrite.conf:/data/etc/httpd/conf.d/ipa-rewrite.conf"
    # https://github.com/freeipa/freeipa-container/commit/9f49a2ffff86fc441e8ac6cbcfb68526add42769
    dns_servers:
      - 127.0.0.1
    ports:
      - "{{ ip }}:80:80"
      - "{{ ip }}:443:443"
      - "{{ ip }}:389:389"   # ldap
      - "{{ ip }}:636:636"   # ldaps
      - "{{ ip }}:88:88"     # kerberos
      - "{{ ip }}:464:464"   # kpasswd 
      - "{{ ip }}:749:749"   # kpasswd
      - "{{ ip }}:123:123"   # ntp
      - "{{ ip }}:53:53"   # dns
    tmpfs:
      - "/run"
      - "/tmp"
    sysctls:
      # Fixes:
      # DEBUG The ipa-server-install command failed, exception: 
      # RuntimeError: IPv6 stack is enabled in the kernel but there is no interface that has ::1 address assigned.
      # Add ::1 address resolution to "lo" interface. You might need to enable IPv6 on the interface "lo" in sysctl.conf.
      net.ipv6.conf.lo.disable_ipv6: 0

- name: "Wait for install to finish (8-12 minutes, check {{ mount }}/freeipa-data/var/log/ipa-server-configure-first.log if time out)"
  become: yes
  wait_for:
    path: "{{ mount }}/freeipa-data/var/log/ipaserver-install.log"
    search_regex: "The ipa-server-install command was successful"
    timeout: 1200 # 20 minutes

- name: "Wait"
  pause:
    seconds: 5