
- name: Fetch ISO from URL & verify checksum
  get_url:
    url: "{{ packer_vars.iso_url }}"
    dest: "/var/lib/vz/template/iso/{{ packer_vars.iso_file }}"
    checksum: "{{ packer_vars.iso_checksum }}"

- name: Ensure packer directory on server
  file:
    path: /root/NaC/packer
    state: directory
    mode: '0700'

- name: Ensure template provisioning folder on server
  file:
    path: "/root/NaC/{{ provision_directory }}"
    state: directory
    mode: '0700'

- name: Ensure provision directory copied to server
  synchronize:
    src: "./{{ provision_directory }}"
    dest: "/root/NaC/packer/."

# - name: Ensure any templates in provisioning directory, provisioned
#   template:
#     src: "{{ item }}"
#     dest: "/root/NaC/packer/{{ template_name }}/{{ item | basename | regex_replace('\\.j2', '') }}"
#   with_fileglob:
#     - "./{{ provision_directory }}/*.j2"

- set_fact:
    packer_vars_argument: ""

- name: Build packer vars
  set_fact:
    packer_vars_argument: "{{ packer_vars_argument }} -var '{{ item.key }}={{ item.value }}' "
  loop: "{{ packer_vars | dict2items }}"

- name: a
  debug:
    msg: "packer build -var 'proxmox_api_url={{ proxmox_api_url }}' -var 'proxmox_username={{ proxmox_username }}' -var 'proxmox_password={{ proxmox_password }}' -var 'proxmox_node={{ proxmox_node }}' {{ packer_vars_argument }} packer.json"

- name: Call packer
  become: yes
  command:
    chdir: "/root/NaC/{{ provision_directory }}"
    cmd: "packer build -var 'proxmox_api_url={{ proxmox_api_url }}' -var 'proxmox_username={{ proxmox_username }}' -var 'proxmox_password={{ proxmox_password }}' -var 'proxmox_node={{ proxmox_node }}' {{ packer_vars_argument }} packer.json"
  register: io

- debug: msg="{{ io.stdout }}"
- debug: msg="{{ io.stderr }}"
      