---
- name: Ensure netsoc.co Docker Container
  become: yes
  docker_stack:
    state: present
    name: netsoc_co
    # with_registry_auth: true
    compose:
      - version: "3.7"
        services:
          nginx:
            image: docker.netsoc.co/public/netsoc.co:latest
            networks:
              traefik:
            deploy:
              mode: global
              placement:
                constraints:
                  - node.hostname == {{ inventory_hostname }}
                preferences:
                  - spread: node.id
              labels:
                - "traefik.enable=true"
                - "traefik.http.routers.netsoc_co.rule=Host(`netsoc.co`) || Host(`www.{{ co_site }}`)"
                - "traefik.http.routers.netsoc_co.entrypoints=web-secure"
                - "traefik.http.routers.netsoc_co.tls.certResolver=letsencrypt"
                - "traefik.http.services.netsoc_co-service.loadbalancer.server.port=80"
                - "traefik.http.routers.netsoc_co.service=netsoc_co-service"
                - "traefik.http.middlewares.rk-redirect.redirectregex.regex=^https://netsoc.co/(r(?:[^k].*)|[^r].*)?$$"
                - "traefik.http.middlewares.rk-redirect.redirectregex.replacement=https://netsoc.co/rk/$${1}"
                - "traefik.http.middlewares.rk-redirect.redirectregex.permanent=true"
                - "traefik.http.middlewares.rk-strip.stripprefix.prefixes=/rk"
                - "traefik.http.routers.netsoc_co.middlewares=rk-redirect@docker,rk-strip@docker"
                - "traefik.docker.network=traefik"
              restart_policy:
                condition: any
                delay: 5s
                max_attempts: 5
        networks:
          traefik:
            external: true  