---
- name: Set vm.max_map_count sysctl
  become: yes
  sysctl:
    name: vm.max_map_count
    value: '262144'
    state: present

- name: Ensure /netsoc/docker-data/elasticsearch created with 0700
  become: yes
  file:
    path: /netsoc/docker-data/elasticsearch
    owner: netsoc
    group: netsoc
    mode: 0777
    state: directory

- name: Ensure Elasticsearch network
  become: yes
  docker_network:
    name: elasticsearch
    driver: overlay
    attachable: yes

- name: Ensure elasticsearch
  become: yes
  docker_stack:
    state: present
    name: elasticsearch
    compose:
      - version: '3.7'
        networks:
          elasticsearch:
            external: true
        services:
          elasticsearch:
            image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
            container_name: elasticsearch
            volumes:
              - /netsoc/docker-data/elasticsearch:/usr/share/elasticsearch/data
            environment:
              discovery.type: single-node
              xpack.security.enabled: 'false'
              xpack.ml.enabled: 'false'
            networks:
              - elasticsearch
            ulimits:
              nofile:
                soft: 122880
                hard: 122880              
            ports:
              - 9200:9200
              - 9300:9300
            deploy:
              mode: global
              placement:
                constraints:
                  - node.role == manager
                  - node.hostname == {{ inventory_hostname }}
              restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3