---

- name: Ensure /netsoc-neo/docker-data/traefik created with 0775
  become: yes
  file:
    path: /netsoc-neo/docker-data/traefik
    owner: root
    group: root
    mode: 0770
    state: directory

- name: Ensure /netsoc-neo/docker-data/traefik/dynamic_config created with 0775
  become: yes
  file:
    path: /netsoc-neo/docker-data/traefik/dynamic_config
    owner: root
    group: root
    mode: 0770
    state: directory

- name: Sync files for /netsoc-neo/docker-data/traefik/dynamic_config/* to /traefik/dynamic_config/"
  become: yes
  synchronize:
    src: files/dynamic_config/
    dest: /netsoc-neo/docker-data/traefik/dynamic_config/
    perms: no # Don't preserve permissions
    delete: yes # Remove files that do not exist in src from dest
    recursive: true
  # copy:
  #   src: "{{ item.src }}"
  #   dest: "/netsoc-neo/docker-data/traefik/dynamic_config/{{ item.path }}"
  #   owner: root
  #   group: root
  #   mode: "{{ item.mode }}"
  #   backup: yes
  # with_filetree:
  #   - files/dynamic_config
  # when: item.state == "file"


- name: Copy Traefik Static Config
  become: yes
  copy:
    src: files/static_config.toml
    dest: /netsoc-neo/docker-data/traefik/static_config.toml

- name: Ensure Cloudflare DNS token in Docker Swarm Secrets
  run_once: true
  become: yes
  docker_secret:
    name: cloudflare_dns_api_token.txt
    data: "{{ cloudflare_dns_api_token }}"
  register: result
  ignore_errors: true

- name: Remove Consul Config Secret from Swarm Service to update the Secret
  become: yes
  docker_stack:
    state: absent
    absent_retries: 5
    name: cloudflare_dns_api_token.txt
  when: result is failed

- name: Retry setting Consul Config in Docker Swarm Secrets if necessary
  run_once: true
  when: result is failed
  become: yes
  docker_secret:
    name: cloudflare_dns_api_token.txt
    data: "{{ cloudflare_dns_api_token }}"


- name: Ensure Traefik Docker network
  become: yes
  docker_network:
    name: traefik
    driver: overlay
    attachable: yes

- name: Ensure Traefik Docker container
  become: yes
  docker_stack:
    state: present
    name: traefik
    compose:
      - version: "3.5"
        services:
          server:
            image: traefik:2.1.3
            ports:
              - target: 80
                published: 80
                protocol: tcp
                mode: host
              - target: 443
                published: 443
                protocol: tcp
                mode: host
            networks:
              traefik:
            deploy:
              mode: global
              placement:
                constraints:
                  - node.role == manager
                  - node.hostname == {{ inventory_hostname }}
                preferences:
                  - spread: node.id
              restart_policy:
                condition: any
                delay: 2s
                max_attempts: 1
              labels:
                # global redirect to https
                - "traefik.enable=true"
                - "traefik.docker.network=traefik"
                - "traefik.http.routers.https-redirect.entrypoints=web"
                - "traefik.http.routers.https-redirect.rule=HostRegexp(`{any:.*}`)"
                - "traefik.http.routers.https-redirect.middlewares=https-redirect"
                - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
                - "traefik.http.middlewares.https-redirect.redirectscheme.port=443"
                - "traefik.http.middlewares.https-redirect.redirectscheme.permanent=true"

                # passworded dashboard
                - "traefik.http.routers.dashboard.entrypoints=web-secure"
                - "traefik.http.routers.dashboard.rule=Host(`traefik.netsoc.dev`)"
                - "traefik.http.routers.dashboard.tls.certResolver=letsencrypt"
                - "traefik.http.routers.dashboard.service=dashboard-service"
                - "traefik.http.services.dashboard-service.loadbalancer.server.port=8080"
                - "traefik.http.middlewares.dashboard-auth.basicauth.users={{ traefik_basic_auth }}"
                - "traefik.http.routers.dashboard.middlewares=dashboard-auth@docker"

            volumes:
              - /var/run/docker.sock:/var/run/docker.sock
              - /netsoc-neo/docker-data/traefik/:/traefik/
            command: traefik --configFile=/traefik/static_config.toml
            secrets:
              - "cloudflare_dns_api_token.txt"
            environment:
              CLOUDFLARE_DNS_API_TOKEN_FILE: "/run/secrets/cloudflare_dns_api_token.txt"
          whoami:
            deploy:
              mode: global
              placement:
                constraints:
                  # - node.role == manager
                  - node.hostname == {{ inventory_hostname }}
                preferences:
                  - spread: node.id
              restart_policy:
                condition: any
                delay: 10s
                max_attempts: 1
              labels:
                - "traefik.enable=true"
                - "traefik.http.routers.whoami.rule=Host(`whoami.netsoc.dev`)"
                - "traefik.http.routers.whoami.entrypoints=web-secure"
                - "traefik.http.routers.whoami.tls.certResolver=letsencrypt"
                - "traefik.http.services.whoami-service.loadbalancer.server.port=80"
                - "traefik.http.routers.whoami.service=whoami-service"
                - "traefik.docker.network=traefik"
            image: "containous/whoami"
            # container_name: "simple-service"
            networks:
              traefik:
        secrets:
          cloudflare_dns_api_token.txt:
            external: true
        networks:
          traefik:
            external: true